#!/usr/bin/env python3
"""Generate the human and agent capability/claim maps from runtime truth."""

import copy
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from srdcheck.access import capabilities, default_adapter_paths  # noqa: E402
from srdcheck.adapter import Adapter  # noqa: E402
from srdcheck.contract import CLAIMS_SCHEMA_VERSION  # noqa: E402


def build():
    caps = capabilities()
    adapters = {a.manifest["name"]: a for a in
                (Adapter(path) for path in default_adapter_paths())}
    shipped = []
    for source in caps["query_coverage"]:
        entry = copy.deepcopy(source)
        owner = entry["adapter"]
        query_type = entry["query_type"]
        entry["tool"] = query_type.replace(".", "_").replace("-", "_")
        if owner == "kernel":
            entry["description"] = (
                "Registry-membership gate shared by loaded adapters.")
        else:
            adapter = adapters[owner]
            entry["adapter_versions"] = {
                "adapter": adapter.manifest["version"],
                "data": adapter.data_version,
                "rules": adapter.rules_version,
            }
            entry["description"] = adapter.query_meta[query_type]["description"]
        shipped.append(entry)
    return {
        "schema_version": CLAIMS_SCHEMA_VERSION,
        "generated_from": (
            "srdcheck/capability_claims.json + srdcheck capabilities + "
            "adapter queries.json"),
        "engine": caps["engine"],
        "machine_contracts": caps["machine_contracts"],
        "release_tuple": caps["release_tuple"],
        "refusal_contract": caps["refusal_contract"],
        "result_contract": caps["result_contract"],
        "shipped": shipped,
        "targets": caps["targets"],
    }


def render_json():
    return json.dumps(build(), indent=1, ensure_ascii=False) + "\n"


def _items(values):
    return "; ".join(values)


def render_markdown():
    doc = build()
    promise = doc["result_contract"]
    lines = [
        "# Capability, coverage, and claim map",
        "",
        "> Generated by `scripts/capability_map.py`; CI checks freshness. "
        "Use the JSON companion for agent consumption.",
        "",
        "## Result contract",
        "",
        f"- **Canonical promise:** {promise['canonical_promise']}",
        f"- **Authority:** {promise['authority_boundary']}",
        f"- **Prose:** {promise['prose_stability']}",
        f"- **Vision:** {promise['vision_rule']}",
        "",
        "## Exit-2 recovery contract",
        "",
        "Machine metadata lives in `data`; agents branch on it instead of "
        "parsing `why`. An authorized agent-DM may resolve a DM-authority "
        "table ruling directly.",
        "",
        "| reason | recoverability | default next action | authority |",
        "|---|---|---|---|",
    ]
    for reason, recovery in doc["refusal_contract"]["reason_mappings"].items():
        lines.append(
            f"| `{reason}` | `{recovery['recoverability']}` | "
            f"`{recovery['suggested_next_action']}` | "
            f"`{recovery.get('required_authority', '—')}` |")
    lines.extend([
        "",
        "## Release identity",
        "",
        f"Engine `{doc['engine']['version']}`; verdict schema "
        f"`{doc['machine_contracts']['verdict_schema_version']}`; "
        f"compatibility `{doc['machine_contracts']['compatibility_window']}` "
        f"over `{', '.join(doc['machine_contracts']['supported_engine_minors'])}`.",
        "",
        "| adapter | adapter version | data version | rules version | digest |",
        "|---|---:|---:|---:|---|",
    ])
    for adapter in doc["release_tuple"]["adapters"]:
        lines.append(
            f"| `{adapter['identifier']}` | `{adapter['version']}` | "
            f"`{adapter['data_version']}` | `{adapter['rules_version']}` | "
            f"`{adapter['digest'][:12]}…` |")
    lines.extend([
        "",
        "## Shipped, executable today",
        "",
        "A `legal` result below means only that the named checked scope passed.",
        "",
        "| tool | capability | checked scope | explicitly unchecked | evidence |",
        "|---|---|---|---|---|",
    ])
    for item in doc["shipped"]:
        evidence = "; ".join(f"`{path}`" for path in item["evidence"])
        lines.append(
            f"| `{item['tool']}` | {item['capability']} | "
            f"{_items(item['checked_scope'])} | "
            f"{_items(item['unchecked_scope'])} | {evidence} |")
    lines.extend([
        "",
        "## Target architecture — not shipped",
        "",
        "These entries are roadmap intent, not executable capability claims.",
        "",
        "| target | intended capability | current truth |",
        "|---|---|---|",
    ])
    for item in doc["targets"]:
        lines.append(
            f"| `{item['id']}` | {item['capability']} | {item['not_shipped']} |")
    return "\n".join(lines) + "\n"


def main():
    (ROOT / "docs/capability-map.json").write_text(render_json(),
                                                    encoding="utf-8")
    (ROOT / "docs/capability-map.md").write_text(render_markdown(),
                                                  encoding="utf-8")
    print("wrote docs/capability-map.json and docs/capability-map.md")


if __name__ == "__main__":
    main()
