#!/usr/bin/env python3
"""Generate the atom concordance: every rule srdcheck applies, mapped to its SRD
citation, forward (atom -> page) and inverse (page -> atoms).

Why this exists: a large context window can *read* the SRD. srdcheck's value is
the layer above that — a consistent, cited set of rule atoms and a shared schema
that multiple agents can rely on without each re-deriving the rules into context
(and drifting from one another). This artifact makes that layer auditable: a
human can see exactly which SRD text each atom is grounded in, and an agent can
load the slim JSON index to know what the rail covers and where it comes from.

Outputs (committed, CI-freshness-checked):
  docs/atom-concordance.md    human-readable, forward + inverse tables
  docs/atom-concordance.json  machine index: {atoms: {...}, by_page: {...}}

Regenerate: python scripts/concordance.py
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
ADAPTERS = ROOT / "srdcheck" / "adapters"
# adapters that carry adjudication atoms (srd-5.1 is a data/name adapter)
WITH_ATOMS = ["srd-5.2.1", "toy-tictactoe"]


def _rows():
    rows = []
    for name in WITH_ATOMS:
        adir = ADAPTERS / name
        manifest = json.loads((adir / "manifest.json").read_text())
        ruleset = manifest.get("ruleset", name)
        version = f"{name}@{manifest['version']}"
        for f in sorted((adir / "atoms").glob("*.json")):
            for atom in json.loads(f.read_text()):
                c = atom.get("citation") or {}
                if not c.get("quote"):
                    continue
                rows.append({
                    "atom": atom["id"],
                    "adapter": name,
                    "version": version,
                    "ruleset": ruleset,
                    "page": c.get("page"),
                    "section": c.get("section", ""),
                    "quote": c["quote"],
                })
    return rows


def build_json(rows):
    atoms = {}
    by_page = {}
    for r in rows:
        atoms[r["atom"]] = {"adapter": r["adapter"], "page": r["page"],
                            "section": r["section"], "quote": r["quote"]}
        key = f"{r['adapter']} p.{r['page']}" if r["page"] is not None \
            else f"{r['adapter']} {r['section']}"
        by_page.setdefault(key, []).append(r["atom"])
    return {"generated_by": "scripts/concordance.py",
            "atoms": dict(sorted(atoms.items())),
            "by_page": {k: sorted(v) for k, v in sorted(by_page.items())}}


def build_md(rows):
    versions = sorted({r["version"] for r in rows})
    out = [
        "# Atom concordance",
        "",
        "Every rule **srdcheck** applies, mapped to the exact SRD text it is "
        "grounded in — forward (atom → page) and inverse (page → atoms).",
        "",
        "A large context window can *read* the SRD. srdcheck's value is the layer "
        "above: a consistent, cited set of rule atoms and a shared schema that "
        "several agents can rely on without each re-deriving the rules into "
        "context and drifting apart. This table is the audit trail for that layer "
        "— human-checkable here, and machine-readable as "
        "[`atom-concordance.json`](atom-concordance.json).",
        "",
        "> Generated by `scripts/concordance.py`; never hand-edited (CI checks it "
        "is fresh). Quoted text is from the System Reference Document "
        "(SRD 5.2.1 and 5.1), © Wizards of the Coast, licensed under "
        "[CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/legalcode); see "
        "each adapter's manifest for full attribution.",
        "",
        f"Adapters: {', '.join(f'`{v}`' for v in versions)}.",
        "",
    ]
    # forward, grouped by adapter
    for name in WITH_ATOMS:
        sub = sorted((r for r in rows if r["adapter"] == name),
                     key=lambda r: r["atom"])
        if not sub:
            continue
        out += [f"## `{sub[0]['version']}` — {sub[0]['ruleset']} ({len(sub)} atoms)",
                "", "| Atom | Page | Rule (verbatim) |", "|---|---|---|"]
        for r in sub:
            pg = f"p.{r['page']}" if r["page"] is not None else "—"
            q = r["quote"].replace("|", "\\|")
            out.append(f"| `{r['atom']}` | {pg} | {q} |")
        out.append("")
        # inverse for this adapter
        pages = {}
        for r in sub:
            pages.setdefault(r["page"], []).append(r["atom"])
        out += ["### By page", ""]
        for pg in sorted(pages, key=lambda x: (x is None, x)):
            label = f"**p.{pg}**" if pg is not None else "**(no page)**"
            out.append(f"- {label} — " + ", ".join(f"`{a}`" for a in sorted(pages[pg])))
        out.append("")
    return "\n".join(out)


def main():
    rows = _rows()
    docs = ROOT / "docs"
    (docs / "atom-concordance.md").write_text(build_md(rows))
    (docs / "atom-concordance.json").write_text(
        json.dumps(build_json(rows), indent=1, ensure_ascii=False) + "\n")
    print(f"wrote docs/atom-concordance.md and .json — {len(rows)} atoms")


if __name__ == "__main__":
    main()
