#!/usr/bin/env python3
"""Generate the README truth scorecard (product truths T1-T13 vs reality).

Interpolates only deterministic numbers (atom counts, test counts, bench
inventory) so regeneration is stable; the latency and correctness gates
themselves live in the test suite. --check regenerates and exits nonzero
if the README section changed (CI freshness gate — never hand-edited).
"""

import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
START = "<!-- truth-scorecard:start -->"
END = "<!-- truth-scorecard:end -->"


def facts():
    atoms = []
    for f in (ROOT / "srdcheck" / "adapters").glob("*/atoms/*.json"):
        atoms += json.loads(f.read_text())
    quoted = sum(1 for a in atoms if a["citation"].get("quote"))
    collected = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "tests/"],
        capture_output=True, text=True, cwd=ROOT).stdout
    ntests = sum(1 for l in collected.splitlines() if "::" in l)
    card = json.loads((ROOT / "bench" / "scorecard.json").read_text())
    subjects = {s for v in card.values() for s in v}
    sys.path.insert(0, str(ROOT))
    from srdcheck.mcp import Server
    ntools = len(Server().tools)
    return dict(atoms=len(atoms), quoted=quoted, ntests=ntests,
                nsets=len(card), nsubjects=len(subjects), ntools=ntools)


def table(f):
    rows = [
        ("T1", "wrong verdicts", "enforced in CI",
         f"{f['ntests']} tests including gold suites ported from the Phase 0 "
         "eval; any wrong verdict fails the build"),
        ("T2", "no citation, no rule", "enforced in CI",
         f"{f['quoted']}/{f['atoms']} rule atoms carry verbatim source "
         "quotes; every-verdict-cites tests on all adjudicated paths"),
        ("T3", "advise, never overrule", "structural",
         "the API has no blocking or veto interface to wire; verdicts are "
         "advisory by construction"),
        ("T4", "one payload, two audiences", "enforced in CI",
         "every verdict carries machine fields plus a templated plain-English "
         "why; schema-tested"),
        ("T5", "enumeration is the product", "proven in CI",
         "consistency sweeps (50 turn states + toy boards) verify "
         "enumerate/validate agreement in both directions on every push"),
        ("T6", "judge, never simulate", "enforced in CI",
         "determinism test (identical verdicts across repeated queries); "
         "kernel verdict path holds no RNG, network, or owned state"),
        ("T7", "mechanism never knows the game", "enforced in CI",
         "kernel lint scans every kernel module for game vocabulary "
         "(it caught a real violation during development)"),
        ("T8", "honest boundaries", "enforced in CI",
         "refusal goldens: unknown content, unmodeled conditions, and "
         "genuinely ambiguous rules text all return exit 2 with citations"),
        ("T9", "never a single number", "enforced in CI",
         "bench scorecard freshness test; per-category tables, no aggregate "
         "score exists anywhere in this repository"),
        ("T10", "stranger-agent bootstrap", "partial",
         f"CLI, --pipe, --schema, tool.json, pip install, and an MCP server "
         f"exposing {f['ntools']} tools are shipped; the standing cold-start "
         "agent eval is not built yet"),
        ("T11", "table speed", "enforced in CI",
         "p95 latency budget test: 100 verdicts must stay under 100 ms at "
         "p95 (typically sub-millisecond)"),
        ("T12", "never sell what the model has", "held in review",
         "a strategy invariant: features pitched on knowledge parity are "
         "cut in review — enforced by humans and admitted as such"),
        ("T13", "the benchmark is a product", "shipped",
         f"bench/ publishes {f['nsets']} sets across {f['nsubjects']} "
         "subjects with cited gold verdicts; cmd: driver lets any agent "
         "benchmark itself"),
    ]
    lines = ["| truth | claim | status | evidence |", "|---|---|---|---|"]
    for t, claim, status, ev in rows:
        lines.append(f"| {t} | {claim} | {status} | {ev} |")
    return "\n".join(lines)


def main():
    body = (f"{START}\n"
            "Generated by `scripts/truth_scorecard.py` — regenerated and "
            "diff-checked in CI, never hand-edited. Statuses are honest: "
            "*structural* and *held in review* mean exactly that.\n\n"
            f"{table(facts())}\n{END}")
    text = README.read_text()
    if START in text:
        new = re.sub(re.escape(START) + ".*?" + re.escape(END), body,
                     text, flags=re.DOTALL)
    else:
        new = text.replace(
            "*(No releases yet. First scorecard ships with v0.1.)*", body)
    changed = new != text
    README.write_text(new)
    if "--check" in sys.argv:
        sys.exit(1 if changed else 0)
    print("scorecard", "updated" if changed else "unchanged")


if __name__ == "__main__":
    main()
